services:
  - type: web
    name: taskforge-backend
    env: python
    region: oregon
    plan: free
    buildCommand: cd backend && python manage.py migrate && python manage.py collectstatic --no-input
    startCommand: cd backend && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.2
      - key: DEBUG
        value: "True"
      - key: DB_ENGINE
        value: django.db.backends.sqlite3
