# Generated by Django 4.2.17 on 2026-04-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_timelog_taskhistory_taskattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='task',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='user',
        ),
        migrations.DeleteModel(
            name='TaskAttachment',
        ),
        migrations.DeleteModel(
            name='TaskHistory',
        ),
        migrations.DeleteModel(
            name='TimeLog',
        ),
    ]
