# Generated by Django 4.2.11 on 2026-04-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_subtask_parent"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="subtask",
            new_name="subtasks_task_id_491407_idx",
            old_name="subtasks_task_parent_order_idx",
        ),
    ]
